[assembly: System.Reflection.AssemblyCompany("QuickWaifu2x")]
[assembly: System.Reflection.AssemblyConfiguration("Debug")]
[assembly: System.Reflection.AssemblyProduct("QuickWaifu2x")]
[assembly: System.Reflection.AssemblyTitle("QuickWaifu2x")]
[assembly: System.Reflection.AssemblyVersion("1.1.*")]